// Centralized learning modules catalog (pure data, no React)
// Do NOT include UI-derived fields like `unlocked` here; those are computed in components/hooks.

export const modulesCatalog = [
    // Verbal Reasoning Modules
    {
        id: "vocabulary-foundation",
        title: "Vocabulary Foundation",
        description: "Build your vocabulary foundation with essential words and strategies",
        category: "verbal",
        difficulty: "beginner",
        estimatedTime: 45,
        totalQuestions: 25,
        xpReward: 100,
        conceptsCount: 8,
        practiceProblems: 15,
        featured: true,
        rating: 4.8,
        enrolledCount: 12543,
        completionRate: 87,
        tags: ["vocabulary", "fundamentals", "beginner-friendly"],
        prerequisite: null,
        learningObjectives: [
            "Master 200+ essential vocabulary words",
            "Learn root words and prefixes",
            "Practice context-based vocabulary questions",
            "Develop memory techniques for retention",
        ],
    },
    {
        id: "advanced-vocabulary",
        title: "Advanced Vocabulary Mastery",
        description: "Master sophisticated vocabulary for high-level test performance",
        category: "verbal",
        difficulty: "advanced",
        estimatedTime: 75,
        totalQuestions: 40,
        xpReward: 200,
        conceptsCount: 12,
        practiceProblems: 25,
        featured: false,
        rating: 4.9,
        enrolledCount: 8392,
        completionRate: 78,
        tags: ["vocabulary", "advanced", "high-frequency"],
        prerequisite: "vocabulary-foundation",
        learningObjectives: [
            "Learn 500+ advanced vocabulary words",
            "Master nuanced word meanings",
            "Practice advanced sentence completion",
            "Develop sophisticated writing vocabulary",
        ],
    },
    {
        id: "reading-comprehension-basics",
        title: "Reading Comprehension Fundamentals",
        description: "Master the art of understanding and analyzing complex passages",
        category: "verbal",
        difficulty: "intermediate",
        estimatedTime: 60,
        totalQuestions: 30,
        xpReward: 150,
        conceptsCount: 10,
        practiceProblems: 20,
        featured: true,
        rating: 4.7,
        enrolledCount: 15678,
        completionRate: 82,
        tags: ["reading", "comprehension", "analysis"],
        prerequisite: null,
        learningObjectives: [
            "Learn active reading strategies",
            "Practice identifying main ideas",
            "Master inference techniques",
            "Develop speed reading skills",
        ],
    },
    {
        id: "critical-reasoning",
        title: "Critical Reasoning Mastery",
        description: "Develop logical thinking and argument analysis skills",
        category: "verbal",
        difficulty: "advanced",
        estimatedTime: 90,
        totalQuestions: 35,
        xpReward: 250,
        conceptsCount: 15,
        practiceProblems: 30,
        featured: false,
        rating: 4.6,
        enrolledCount: 7234,
        completionRate: 71,
        tags: ["logic", "reasoning", "arguments"],
        prerequisite: "reading-comprehension-basics",
        learningObjectives: [
            "Analyze logical arguments",
            "Identify assumptions and conclusions",
            "Practice strengthening/weakening arguments",
            "Master formal logic principles",
        ],
    },
    // Quantitative Modules
    {
        id: "arithmetic-fundamentals",
        title: "Arithmetic & Number Properties",
        description: "Master basic arithmetic and number theory concepts",
        category: "quantitative",
        difficulty: "beginner",
        estimatedTime: 50,
        totalQuestions: 35,
        xpReward: 120,
        conceptsCount: 12,
        practiceProblems: 25,
        featured: true,
        rating: 4.8,
        enrolledCount: 18456,
        completionRate: 89,
        tags: ["arithmetic", "numbers", "basics"],
        prerequisite: null,
        learningObjectives: [
            "Master basic arithmetic operations",
            "Understand number properties",
            "Learn divisibility rules",
            "Practice mental math techniques",
        ],
    },
    {
        id: "algebra-mastery",
        title: "Algebra & Equations",
        description: "Solve complex algebraic equations and inequalities",
        category: "quantitative",
        difficulty: "intermediate",
        estimatedTime: 80,
        totalQuestions: 45,
        xpReward: 180,
        conceptsCount: 16,
        practiceProblems: 35,
        featured: false,
        rating: 4.5,
        enrolledCount: 13287,
        completionRate: 76,
        tags: ["algebra", "equations", "functions"],
        prerequisite: "arithmetic-fundamentals",
        learningObjectives: [
            "Solve linear and quadratic equations",
            "Master systems of equations",
            "Understand function concepts",
            "Practice word problems",
        ],
    },
    {
        id: "geometry-coordinate",
        title: "Geometry & Coordinate Systems",
        description: "Master geometric concepts and coordinate geometry",
        category: "quantitative",
        difficulty: "intermediate",
        estimatedTime: 70,
        totalQuestions: 40,
        xpReward: 160,
        conceptsCount: 14,
        practiceProblems: 30,
        featured: true,
        rating: 4.7,
        enrolledCount: 11543,
        completionRate: 80,
        tags: ["geometry", "coordinates", "shapes"],
        prerequisite: "arithmetic-fundamentals",
        learningObjectives: [
            "Calculate areas and perimeters",
            "Master coordinate geometry",
            "Understand geometric properties",
            "Practice 3D geometry",
        ],
    },
    {
        id: "data-analysis",
        title: "Data Analysis & Statistics",
        description: "Analyze data, interpret charts, and understand statistics",
        category: "quantitative",
        difficulty: "advanced",
        estimatedTime: 85,
        totalQuestions: 38,
        xpReward: 220,
        conceptsCount: 18,
        practiceProblems: 32,
        featured: false,
        rating: 4.6,
        enrolledCount: 9876,
        completionRate: 73,
        tags: ["statistics", "data", "analysis"],
        prerequisite: "algebra-mastery",
        learningObjectives: [
            "Interpret statistical data",
            "Calculate probability",
            "Analyze charts and graphs",
            "Understand distributions",
        ],
    },
    // (Trimmed for brevity: include the remaining modules from the previous inline list as needed)
];

// Difficulty string -> numeric rank used for unlock thresholds
export const DIFFICULTY_RANK = {
    beginner: 1,
    intermediate: 2,
    advanced: 3,
    expert: 4,
};

export const getDifficultyRank = (difficulty) => DIFFICULTY_RANK[difficulty] || 1;

export default modulesCatalog;
